### ISSUE TITLE
Missing some intellisense

### ISSUE THREAD

**Issue by erw13n** [vue-typed/vue-typed#3]
I test converting component wrote in Js into Typescript, which is works fine.
Unfortunately its missing some intellisense, like 'created, methods, computed'

for example :
```
@Component({
    template: `
                <div>
                    <a class="cloud-package" v-bind:class="[activePackage == index ? 'active' : '']" v-for="(item, index) in packages" v-on:click="activated(index)">
					    <h2>{{ item.label }}</h2>
	    		    </a>
                </div>
            `,
    data() {
        return {
            packages: [
                { id: 1, label: 'AAA' },
                { id: 2, label: 'BBB' },
                { id: 3, label: 'CCC },
                { id: 4, label: 'DDD' }
            ],
            activePackage: null
        }
    },
    methods: {
        activated: function (item) {
            this.activePackage = item
        }
    }
})
```

**Comment by erw13n** [comment]
And please provide more sample :)

**Comment by erw13n** [comment]
Try to follow your sample, and convert it to 

```
import { Component } from "vue-typed";

var itemPackage = {
    template: `
                <div>
                    <a class="cloud-package" v-bind:class="[activePackage == index ? 'active' : '']" href="javascript:;" v-for="(item, index) in packages" v-on:click="activated(index)">
					    <h2>{{ item.label }}</h2>
	    		    </a>
                </div>
            `,
}
@Component(itemPackage)
export class ItemPackage {
    packages= [
        { id: 1, label: 'XERO' },
        { id: 2, label: 'MYOB CLOUD' },
        { id: 3, label: 'QUICKEN CLOUD' },
        { id: 4, label: 'OTHER CLOUD' }
    ]
    activePackage= null

    activated(item) {
        this.activePackage = item
    }
}
```

But it throw an error on click **Uncaught TypeError: activated is not a function(…)**

Am I missing something ?

**Comment by budiadiono** [comment]
Hi @erw13n , thanks for using VueTyped!

I see there are 2 issues here:

## Intellisense

Yes, you're right, that was because of I imported the [type definition](https://github.com/vue-typed/vue-typed/blob/master/index.d.ts#L55-L73) barely from [vue-class-component](https://github.com/vuejs/vue-class-component/blob/26022264fde43c3cd357bc90cbc2acef1adc9fa6/index.d.ts) it was long time ago when I started writing this module that I think it's outdated now.

I was thinking to update it to match with [@types/vue](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/vue/index.d.ts) which is type definitions for vuejs 1.0.21. But again, this won't be fit with newer versions even worst Vue 2.0, that many stuffs has been deprecated and new stuffs added. Maybe I should stop the support for Vue 1.xx bellow, because Vue 2.0 has bundled [type definition](https://github.com/vuejs/vue/tree/dev/types) that we can use it directly as reference.

## Uncaught TypeError: activated is not a function(…)

The `activated` is part of internal [hooks used by `Vue`](https://vuejs.org/v2/api/#activated). You should not name your function with the name that part of internal hooks.

**Comment by pauleveritt** [comment]
@budiadiono I think stopping support for Vue 1.xx is reasonable. "TypeScript and Vue" is a meme much more associated with 2.0, and if it decreases the open-source-volunteer-work you have to do, then do it.

**Comment by budiadiono** [comment]
Hi @pauleveritt, I think that's really good idea 👍 I'll put it on my top priority.

**Comment by budiadiono** [comment]
I've stopped Vue 1 supports in the latest [version](https://github.com/vue-typed/vue-typed/releases/tag/v2.0.2). It should resolve the intellisense issue.  I'm closing this issue now.

**Comment by pauleveritt** [comment]
@budiadiono I just tried 2.0.2 in WebStorm and the generated project works fine, including code completion in the decorator.

**Comment by erw13n** [comment]
Thanks for the update, works fine on Asp.Net Core.

**Comment by budiadiono** [comment]
Awesome! Thank you guys!
